---
title: "sim_combiner"
author: "JLG"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(data.table)
library(tidyverse)
library(car)
library(performance)
library(MASS)
library(fitdistrplus)
library(performance)
library(betareg)
library(gridExtra)
library(sp)
library(adehabitatHR)
library(vtable)

combined_res <- read.csv("R_out/combined_results.csv")
combined_sdd <- read.csv("combined_sdd.csv")

```

#Looking at 100% tree sim only 
```{r 100TP}

combined_sdd %>% filter(percent_tree == 1) -> sdd_p1

#seed dispersal distances per simulation
ggplot(data = sdd_p1, aes(x=distances, col = as.factor(sim_num))) +
  geom_density(alpha = 0.6) 

#dispersal distances of all seeds from all 80 simulations
sdk = ggplot(data = sdd_p1, aes(x=distances)) +
  geom_histogram(aes(y = after_stat(density)), alpha = 0.6, position = "dodge", bins = 30) + 
  geom_density(size = 1) + 
  xlab("Distances from origin tree (m)") +
  theme_classic()

#usign the dataset with summarized results
combined_res %>% filter(percent_tree == 1) -> res_100TP
summary(res_100TP, digits = 2)

#proportion in the forest
g1=ggplot(data = res_100TP, aes(x = n_seed_dispersed)) +
  geom_histogram(alpha = 0.6) +
  xlab("No. of dispersed seeds")+ 
  theme_classic()

#proportion in the forest
g2=ggplot(data = res_100TP, aes(x = p_seed_inforest)) +
  geom_histogram() +
  xlab("Proportion of seeds in forest")+ 
  theme_classic()

# histogram of mean_SDD
g3=ggplot(data = res_100TP, aes(x = as.numeric(mean_sdd))) +
  geom_histogram() + 

  xlab("Mean seed dispersal distances") + 
  theme_classic()

gridExtra::grid.arrange(g1,g2,g3, nrow=2, ncol=2) 

ggplot(res_100TP) +
    geom_col(aes(x = sim_num,
                 y = p_seed_inforest), col = "black", fill = "darkgreen") + 
  labs(x = "Simulation no.", y = "Proportion of seeds in forest") +
  theme_classic()

# figure in the paper
gridExtra::grid.arrange(sdk, g1, nrow=2, ncol=1) 


```



## plots
```{r plots, echo=TRUE}

st(combined_res, digits = 2, group = "percent_tree", group.long = TRUE, fixed.digits = TRUE, numformat = NA, out= "csv", file='TPall_summary.csv') 

st(combined_res, group = "percent_tree") 

#removal of outliers for par_sdd
combined_res %>%
  filter(!par_sdd %in% boxplot.stats(combined_res$par_sdd)$out) -> par_sdd_noout

p1 <- ggplot( data = combined_res, aes(x=as.factor(percent_tree), y=n_seed_dispersed)) +
  geom_boxplot() +
  ylab("No. of dispersed seeds") + xlab("% trees in agriculture") +
  geom_jitter(alpha=0.3, size = 0.2) +
  theme_classic()

p2 <-ggplot(data = combined_res, aes(x=as.factor(percent_tree), y=unique_tree)) +
  geom_boxplot() +
  ylab("No. of trees w/ dispersed seeds") + xlab("% trees in agriculture") +
  geom_jitter(alpha=0.3, size = 0.2) +
  theme_classic()

p3<-ggplot( data = combined_res, aes(x=as.factor(percent_tree), y=p_seed_inforest )) +
  geom_boxplot() +
  ylab("Proportion of seeds in  forest") + xlab("% trees in agriculture") +
  geom_jitter(alpha=0.3, size = 0.2) +
  theme_classic()

p4<-ggplot( data = combined_res, aes(x=as.factor(percent_tree), y=n_feeding_occur)) +
  geom_boxplot() +
  ylab("No. of feeding events") + xlab("% trees in agriculture") +
  geom_jitter(alpha=0.3, size = 0.2) +
  theme_classic()

p5<-ggplot( data = combined_res, aes(x=as.factor(percent_tree), y=area_sdd )) +
  geom_boxplot() +
  ylab("Area of seed dispersal MCP") + xlab("% trees in agriculture") +
  geom_jitter(alpha=0.3, size = 0.2) +
  theme_classic()

p6<-ggplot( data = combined_res, aes(x=as.factor(percent_tree), y=par_sdd )) +
  geom_boxplot() +
  ylab("PAR of seed dispersal MCP") + xlab("% trees in agriculture") +
  geom_jitter(alpha=0.3, size = 0.2) +
  theme_classic()

p7<-ggplot( data = combined_res, aes(x=as.factor(percent_tree), y=mean_sdd )) +
  geom_boxplot() +
  ylab("Mean seed dispersal distance") + xlab("% trees in agriculture") +
  geom_jitter(alpha=0.3, size = 0.2) +
  theme_classic()

p6.noout = ggplot( data = par_sdd_noout, aes(x=as.factor(percent_tree), y=par_sdd )) +
  geom_boxplot() +
  ylab("PAR of seed dispersal MCP") + xlab("% trees in agriculture") +
  geom_jitter(alpha=0.3, size = 0.2) +
  theme_classic()

gridExtra::grid.arrange(p1,p2,p4,p5, p6.noout, nrow=3, ncol=2) 
gridExtra::grid.arrange(p3,p7, nrow=2, ncol=2)

```

#single predictor model analysis for all
```{r analysis, echo=TRUE}
newdata = data.frame(percent_tree=unique(combined_res$percent_tree))

#NUMBER OF SEEDS DISPERSED
model.nb =glm.nb(n_seed_dispersed~percent_tree,data = combined_res)
summary(model.nb)

check_homogeneity(model.nb)
check_overdispersion(model.nb) #underdispersed
check_residuals(model.nb)
check_outliers(model.nb)
qqnorm(residuals(model.nb, type = "deviance"))
qqline(residuals(model.nb, type = "deviance"), col = "red")

#predicted values
pred_nseed = predict(model.nb, newdata=newdata, type="response")
plot(pred_nseed ~ newdata$percent_tree)


#UNIQUE TREES
hist(combined_res$unique_tree)
shapiro.test(combined_res$unique_tree) 

unique_tree.pos = glm(unique_tree~percent_tree,data = combined_res, family= poisson)
summary(unique_tree.pos)

check_model(unique_tree.pos)
check_homogeneity(unique_tree.pos)
check_overdispersion(unique_tree.pos)
check_residuals(unique_tree.pos)
check_outliers(unique_tree.pos)
qqnorm(residuals(unique_tree.pos, type = "deviance"))
qqline(residuals(unique_tree.pos, type = "deviance"), col = "red")

#predicted values
pred_uniqtree = predict(unique_tree.pos, newdata=newdata, type="response")
plot(pred_uniqtree ~ newdata$percent_tree)


#Feeding occured
hist(combined_res$n_feeding_occur)
shapiro.test(combined_res$n_feeding_occur) # not normal

# n_feed_mod = glm(n_feeding_occur~percent_tree,data = combined_res, family = poisson) 
n_feed_mod = glm.nb(n_feeding_occur~percent_tree,data = combined_res) 
summary(n_feed_mod)

check_model(n_feed_mod)
check_homogeneity(n_feed_mod) 
check_overdispersion(n_feed_mod) 
check_residuals(n_feed_mod) 
check_outliers(n_feed_mod)

#predicted values
pred_feedoccur = predict(n_feed_mod, newdata=newdata, type="response")
plot(pred_feedoccur ~ newdata$percent_tree)

#area of MCP
hist(combined_res$area_sdd)
shapiro.test(combined_res$area_sdd) # not normal

#area_sdd_mod = glm(area_sdd~percent_tree,data = combined_res, family = gaussian) #does not satify assumption
area_sdd_mod = glm(area_sdd~percent_tree,data = combined_res, family = Gamma(link = "log"))  #inverse was the default
summary(area_sdd_mod) 

check_model(area_sdd_mod)
check_homogeneity(area_sdd_mod) # non homogenous
check_overdispersion(area_sdd_mod)
check_residuals(area_sdd_mod) 
check_outliers(area_sdd_mod)
qqnorm(residuals(area_sdd_mod, type = "deviance"))
qqline(residuals(area_sdd_mod, type = "deviance"), col = "red")

#predicted values
pred_area = predict(area_sdd_mod, newdata=newdata, type="response")
plot(pred_area ~ newdata$percent_tree)


#mean sdd
hist(combined_res$mean_sdd)
shapiro.test(combined_res$mean_sdd) # not normal
# mean_sdd_mod = glm.nb(mean_sdd~percent_tree,data = sdd_out_df_results) #does not satify assumption

mean_sdd_mod = glm(mean_sdd~percent_tree,data = combined_res, family = Gamma(link = "log")) 
summary(mean_sdd_mod)

check_model(mean_sdd_mod)
check_homogeneity(mean_sdd_mod) # non homogenous
check_overdispersion(mean_sdd_mod)
check_residuals(mean_sdd_mod) 
check_outliers(mean_sdd_mod)
qqnorm(residuals(mean_sdd_mod, type = "deviance"))
qqline(residuals(mean_sdd_mod, type = "deviance"), col = "red")

#predicted values
pred_meansdd = predict(mean_sdd_mod, newdata=newdata, type="response")
plot(pred_meansdd ~ newdata$percent_tree)


#p_seedinforest 
hist(combined_res$p_seed_inforest)
shapiro.test(combined_res$p_seed_inforest) # not normal

# Beta regression can be conducted with the betareg function in the betareg package (Cribari-Neto and Zeileis, 2010).  With this function, the dependent variable varies between 0 and 1, but no observation can equal exactly zero or exactly one.  The model assumes that the data follow a beta distribution.
fit_beta <- betareg(p_seed_inforest~percent_tree,data = combined_res)
summary(fit_beta)
plot(fit_beta)

# #not good fit based on performance
# p_seed_inforest_mod = glm(p_seed_inforest~percent_tree,data = combined_res, family = Gamma(link = "log")) 
# summary(p_seed_inforest_mod)
# 
# check_model(p_seed_inforest_mod)
# check_homogeneity(p_seed_inforest_mod) 
# check_overdispersion(p_seed_inforest_mod) # underdispersed
# check_residuals(p_seed_inforest_mod) #non-uniform
# check_outliers(p_seed_inforest_mod)


#PAR of MCP
hist(combined_res$par_sdd)
shapiro.test(combined_res$par_sdd) # not normal 

#removal of outliers
combined_res %>%
  filter(!par_sdd %in% boxplot.stats(combined_res$par_sdd)$out) -> par_sdd_noout

par_sdd_mod = glm(par_sdd~percent_tree,data = par_sdd_noout, family = Gamma(link = "log")) 
#area_sdd_mod = glm(area_sdd~percent_tree,data = combined_res, family = gaussian) #does not satify assumption
summary(par_sdd_mod)

check_model(par_sdd_mod)
check_homogeneity(par_sdd_mod) 
check_overdispersion(par_sdd_mod)
check_residuals(par_sdd_mod) 
check_outliers(par_sdd_mod)
qqnorm(residuals(par_sdd_mod, type = "deviance"))
qqline(residuals(par_sdd_mod, type = "deviance"), col = "red")

#predicted values
pred_parsdd = predict(par_sdd_mod, newdata=newdata, type="response")
plot(pred_parsdd ~ newdata$percent_tree)

```


#plotting! 
```{r}

#number of seeds ######
pred_nseed = data.frame(percent_tree = newdata$percent_tree, pred = pred_nseed)

(A = ggplot(data = combined_res, aes(x=percent_tree, y=n_seed_dispersed)) +  geom_point(color="darkgrey", alpha = 0.2) +
    geom_point(stat= "summary", fun = "mean", size =2, alpha=0.5) +
    geom_path(stat= "summary", fun = "mean", size =1 , alpha=0.5) +
    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.05, size= 1) +
  theme_classic() +
  ylab("No. of dispersed seeds") + xlab("% trees in agriculture") +
  scale_x_continuous(breaks = seq(0, 1, by = 0.1)) + 
  geom_point(data = pred_nseed, aes(x = percent_tree, y = pred), color = "black",
             fill="yellow", pch = 21, size = 2, stroke=1) +
  labs(tag="A"))

#unique tree ######
pred_uniqtree = data.frame(percent_tree = newdata$percent_tree, pred = pred_uniqtree)

(B = ggplot(data = combined_res, aes(x=percent_tree, y=unique_tree)) +  geom_point(color="darkgrey", alpha = 0.2) +
    geom_point(stat= "summary", fun = "mean", size =2, alpha=0.5) +
    geom_path(stat= "summary", fun = "mean", size =1 , alpha=0.5) +
    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.05, size= 1) +
  theme_classic() +
  ylab("No. of trees w/ dispersed seeds") + xlab("% trees in agriculture") +  scale_x_continuous(breaks = seq(0, 1, by = 0.1)) + 
  geom_point(data = pred_uniqtree, aes(x = percent_tree, y = pred), color = "black", fill="yellow", pch = 21, size = 2, stroke=1) +
  labs(tag="B"))

#feeding occur ######
pred_feedoccur = data.frame(percent_tree = newdata$percent_tree, pred = pred_feedoccur)

(C = ggplot(data = combined_res, aes(x=percent_tree, y=n_feeding_occur)) +  geom_point(color="darkgrey", alpha = 0.2) +
    geom_point(stat= "summary", fun = "mean", size =2, alpha=0.5) +
    geom_path(stat= "summary", fun = "mean", size =1 , alpha=0.5) +
    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.05, size= 1) +  theme_classic() +
  ylab("No. of feeding events") + xlab("% trees in agriculture") +  
  scale_x_continuous(breaks = seq(0, 1, by = 0.1)) + 
  geom_point(data = pred_feedoccur, aes(x = percent_tree, y = pred), color = "black", fill="yellow", pch = 21, size = 2, stroke=1) +
  labs(tag="C"))

#area MCP ######
pred_area = data.frame(percent_tree = newdata$percent_tree, pred = pred_area)

(D = ggplot(data = combined_res, aes(x=percent_tree, y=area_sdd)) +  geom_point(color="darkgrey", alpha = 0.2) +
    geom_point(stat= "summary", fun = "mean", size =2, alpha=0.5) +
    geom_path(stat= "summary", fun = "mean", size =1 , alpha=0.5) +
    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.05, size= 1) +
  theme_classic() +
  ylab("Area of seed dispersal MCP") + xlab("% trees in agriculture") +  
  scale_x_continuous(breaks = seq(0, 1, by = 0.1)) + 
  geom_point(data = pred_area, aes(x = percent_tree, y = pred), color = "black", fill="yellow", pch = 21, size = 2, stroke=1) +
  labs(tag="D"))


#PAR #####
pred_parsdd_data = data.frame(percent_tree = newdata$percent_tree, pred = pred_parsdd, cap = "predicted")

(E = ggplot(data = par_sdd_noout, aes(x=percent_tree, y=par_sdd)) +  geom_point(color="darkgrey", alpha = 0.2) +
    geom_point(stat= "summary", fun = "mean", size =2, alpha=0.5) +
    geom_path(stat= "summary", fun = "mean", size =1 , alpha=0.5) +
    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.05, size= 1) +
  theme_classic() +
  ylab("PAR of seed dispersal MCP") + xlab("% trees in agriculture") +  
  scale_x_continuous(breaks = seq(0, 1, by = 0.1)) + 
  geom_point(data = pred_parsdd_data, aes(x = percent_tree, y = pred), 
             color = "black", fill="yellow", pch = 21, size = 2, stroke = 1) +
  labs(tag="E"))

A+B+C+D+E 

```

Session info
```{r sesh}
devtools::session_info()

```
